In [12]:
import numpy as np

# arr = np.array([1, 2, 3, 4, 5])
#arr = np.array((1, 2, 3, 4, 5, 6))

# 0-D
#arr = np.array(50)

#1-D
#arr = np.array([1,2,3,4,5,6])

#2-D
#arr = np.array([[1,2,3,4], [5,6,7,8]])

#3-D
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr)
print(np.__version__)
print(type(arr))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1.26.3
<class 'numpy.ndarray'>
